[build]
command = "cd exampleSite && hugo --gc --minify"
publish = "exampleSite/public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV           = "production"
HUGO_VERSION       = "0.124.0"
NODE_VERSION       = "v20.11.1"
NPM_VERSION        = "10.5.0"

[context.split1]
command = "cd exampleSite && hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --enableGitInfo"

    [context.split1.environment]
    HUGO_ENV     = "production"
    HUGO_VERSION = "0.124.0"
    NODE_VERSION = "v20.11.1"
    NPM_VERSION  = "10.5.0"

[context.deploy-preview]
command = "cd exampleSite && hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

    [context.deploy-preview.environment]
    HUGO_VERSION = "0.124.0"
    NODE_VERSION = "v20.11.1"
    NPM_VERSION  = "10.5.0"

[context.branch-deploy]
command = "cd exampleSite && hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"

    [context.branch-deploy.environment]
    HUGO_VERSION = "0.124.0"
    NODE_VERSION = "v20.11.1"
    NPM_VERSION  = "10.5.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
