# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example
description = "A simple hugo theme for personal portfolio"
homepage = "https://hugo-toha.github.io/"
license = "MIT"
licenselink = "https://github.com/hugo-toha/toha/blob/master/LICENSE"
min_version = "0.68.0"
name = "Toha"

features = [
  "Minimalist Design",
  "Fully Responsive",
  "Multiple Language Support",
  "Carefully Designed Cards",
  "Experience Timeline",
  "Achievement Gallery",
  "Sidebar to Categorize the Posts",
  "Short Codes",
  "Google Analytics Support",
  "Disqus Comment Support",
]
tags = [
  "Portfolio",
  "Blog",
  "Resume",
  "Projects",
  "Gallery",
  "Multilingual",
  "Minimalist",
  "Responsive",
  "Customizable",
  "Google analytics",
  "Disqus",
  "Bootstrap",
  "Syntax highlighting",
]

[author]
homepage = "https://hossainemruz.github.io"
name = "Emruz Hossain"
