name = "Toha"
license = "MIT"
licenselink = "https://github.com/hugo-toha/toha/blob/master/LICENSE"
description = "A simple hugo theme for personal portfolio"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/hugo-toha/toha"

# If you have a running demo of the theme.
demosite = "https://hugo-toha.github.io/"

tags = [
  "Portfolio",
  "Blog",
  "Resume",
  "Projects",
  "Gallery",
  "Multilingual",
  "Minimalist",
  "Responsive",
  "Customizable",
  "Google analytics",
  "Disqus",
  "Bootstrap",
  "Syntax highlighting",
]
features = [
  "Minimalist Design",
  "Fully Responsive",
  "Multiple Language Support",
  "Carefully Designed Cards",
  "Experience Timeline",
  "Achievement Gallery",
  "Sidebar to Categorize the Posts",
  "Short Codes",
  "Google Analytics Support",
  "Disqus Comment Support",
]

[author]
  homepage = "https://hossainemruz.github.io"
  name = "Emruz Hossain"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"